#!/bin/sh

VDED_BIN=/usr/sbin/vded

if [ -f /etc/defaults/vded ]; then
  . /etc/defaults/vded
elif [ -f /etc/vded/config ]; then
  . /etc/vded/config
fi

$VDED_BIN $VDED_OPTIONS 2>&1 >> /var/log/vded/vded.log &

