#!/bin/bash
#
#	/etc/rc.d/init.d/vded
#
# Starts the vded daemon
#
# chkconfig: 2345 20 80
# description: Aggregation of vector values, submitted to ganglia
# processname: vded

### BEGIN INIT INFO
# Provides: vded
# Defalt-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Aggregation of vector values, submitted to ganglia
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

NAME=vded
VDED_EXE=/usr/sbin/vded
VDED_OPTIONS=
LOGFILE=/var/log/vded.log

[ -x $VDED_EXE ] || exit 0
[ -f /etc/vded/config ] && . /etc/vded/config
if [ "$VDED_PORT" == "" ]; then
  VDED_PORT=48333
fi

mkdir -p /var/lib/vded /var/log

RETVAL=0

#
# See how we were called.
#

start() {
	# Check if it is already running
	if [ ! -f /var/lock/subsys/$NAME ]; then
	    echo -n $"Starting $NAME daemon: "
        # daemon
        $VDED_EXE -daemon $VDED_OPTIONS >> $LOGFILE 2>&1
	      RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
            touch /var/lock/subsys/$NAME
            echo_success
        else
            echo_failure
        fi
	    echo
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping $NAME daemon: "
    rm -f /var/lock/subsys/$NAME
    wget -O /dev/stdout -q "http://localhost:${VDED_PORT}/control?action=shutdown"
    pid=$(ps aux | grep vded | grep -v grep | awk '{print $2}')
    RETVAL=1
    COUNT=0
    while [ $COUNT -lt 10 ]; do
      STILL_HERE=$( nc -z -w 1 localhost $VDED_PORT; echo $? )
      if [ $STILL_HERE -eq 1 ]; then
        kill $pid
      else
        RETVAL=0
        COUNT=10
      fi
    done
    if [ $RETVAL -eq 1 ]; then
      kill -9 $pid
    fi
    echo_success
    echo
    return 0
}


restart() {
	stop
	start
}	

reload() {
	trap "" SIGHUP
	killall -HUP vded
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	reload
	;;
restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/subsys/$NAME ]; then
	    restart
	fi
	;;
status)
	if [ -f /var/lock/subsys/$NAME ]; then
        echo "$NAME is running"
        exit 0
    else
        echo "$NAME is stopped"
        exit 3
    fi
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
	exit 1
esac

exit $RETVAL

